export const labList = [
  {
    name: '304',
    computers: '30',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: true,
    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
    ],
  },
  {
    name: '305',
    computers: '25',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,

    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'BE',
        class: 'C',
      },
      {
        timeSt: '12:00 PM',
        timeEnd: '01:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'C',
      },
      {
        timeSt: '01:00 PM',
        timeEnd: '02:00 PM',
        subject: 'Cloud Computing',
        facultyIncharge1: 'Ritika Sharma',
        facultyIncharge2: 'Rajeev Ranjan',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '02:00 PM',
        timeEnd: '03:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '03:00 PM',
        timeEnd: '04:00 PM',
        subject: 'Big Data',
        facultyIncharge1: 'Manoj Sinha',
        facultyIncharge2: 'Sunita Yadav',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '04:00 PM',
        timeEnd: '05:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'A',
      },
    ],
  },
  {
    name: '306',
    computers: '35',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: true,
    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },

      {
        timeSt: '02:00 PM',
        timeEnd: '03:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '03:00 PM',
        timeEnd: '04:00 PM',
        subject: 'Big Data',
        facultyIncharge1: 'Manoj Sinha',
        facultyIncharge2: 'Sunita Yadav',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '04:00 PM',
        timeEnd: '05:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'A',
      },
    ],
  },
  {
    name: '307',
    computers: '28',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'BE',
        class: 'C',
      },
      {
        timeSt: '12:00 PM',
        timeEnd: '01:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'C',
      },
      {
        timeSt: '01:00 PM',
        timeEnd: '02:00 PM',
        subject: 'Cloud Computing',
        facultyIncharge1: 'Ritika Sharma',
        facultyIncharge2: 'Rajeev Ranjan',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '02:00 PM',
        timeEnd: '03:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '03:00 PM',
        timeEnd: '04:00 PM',
        subject: 'Big Data',
        facultyIncharge1: 'Manoj Sinha',
        facultyIncharge2: 'Sunita Yadav',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '04:00 PM',
        timeEnd: '05:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'A',
      },
    ],
  },
  {
    name: '324',
    computers: '40',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'BE',
        class: 'C',
      },
      {
        timeSt: '12:00 PM',
        timeEnd: '01:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'C',
      },
      {
        timeSt: '01:00 PM',
        timeEnd: '02:00 PM',
        subject: 'Cloud Computing',
        facultyIncharge1: 'Ritika Sharma',
        facultyIncharge2: 'Rajeev Ranjan',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '02:00 PM',
        timeEnd: '03:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '03:00 PM',
        timeEnd: '04:00 PM',
        subject: 'Big Data',
        facultyIncharge1: 'Manoj Sinha',
        facultyIncharge2: 'Sunita Yadav',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '04:00 PM',
        timeEnd: '05:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'A',
      },
    ],
  },
  {
    name: '325',
    computers: '32',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'BE',
        class: 'C',
      },
      {
        timeSt: '12:00 PM',
        timeEnd: '01:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'C',
      },
      {
        timeSt: '01:00 PM',
        timeEnd: '02:00 PM',
        subject: 'Cloud Computing',
        facultyIncharge1: 'Ritika Sharma',
        facultyIncharge2: 'Rajeev Ranjan',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '02:00 PM',
        timeEnd: '03:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '03:00 PM',
        timeEnd: '04:00 PM',
        subject: 'Big Data',
        facultyIncharge1: 'Manoj Sinha',
        facultyIncharge2: 'Sunita Yadav',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '04:00 PM',
        timeEnd: '05:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'A',
      },
    ],
  },
  {
    name: '326',
    computers: '50',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '09:00 AM',
        timeEnd: '10:00 AM',
        subject: 'IoT',
        facultyIncharge1: 'Aakash Roy',
        facultyIncharge2: 'Kavita Iyer',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'BE',
        class: 'C',
      },

      {
        timeSt: '02:00 PM',
        timeEnd: '03:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '03:00 PM',
        timeEnd: '04:00 PM',
        subject: 'Big Data',
        facultyIncharge1: 'Manoj Sinha',
        facultyIncharge2: 'Sunita Yadav',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '04:00 PM',
        timeEnd: '05:00 PM',
        subject: 'Cybersecurity',
        facultyIncharge1: 'Alok Verma',
        facultyIncharge2: 'Deepika Desai',
        year: 'SE',
        class: 'A',
      },
    ],
  },
]

export const classList = [
  {
    name: '603',
    capacity: '70',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'Software Architecture',
        facultyIncharge: 'Tarunima Mukherjee',
        year: 'BE',
        class: 'C',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Cloud Computing',
        facultyIncharge: 'Ravi Verma',
        year: 'TE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Cyber Security',
        facultyIncharge: 'Sneha Rao',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '12:00 PM',
        timeEnd: '1:00 PM',
        subject: 'AI & ML',
        facultyIncharge: 'Pratik Deshmukh',
        year: 'BE',
        class: 'A',
      },

      {
        timeSt: '4:00 PM',
        timeEnd: '5:00 PM',
        subject: 'Blockchain',
        facultyIncharge: 'Ruchi Sharma',
        year: 'BE',
        class: 'B',
      },
    ],
  },
  {
    name: '604',
    capacity: '50',
    open_time: '8:00 AM',
    close_time: '4:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '8:00 AM',
        timeEnd: '9:00 AM',
        subject: 'Discrete Mathematics',
        facultyIncharge: 'Swati Nair',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'Data Science',
        facultyIncharge: 'Kunal Joshi',
        year: 'TE',
        class: 'B',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Data Structures',
        facultyIncharge: 'Amit Bhardwaj',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Microprocessors',
        facultyIncharge: 'Meenal Kulkarni',
        year: 'SE',
        class: 'C',
      },
      {
        timeSt: '12:00 PM',
        timeEnd: '1:00 PM',
        subject: 'Software Testing',
        facultyIncharge: 'Anuj Saxena',
        year: 'TE',
        class: 'C',
      },
    ],
  },
  {
    name: '605',
    capacity: '60',
    open_time: '8:30 AM',
    close_time: '4:30 PM',
    computer_working: false,
    projector_working: false,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '8:30 AM',
        timeEnd: '9:30 AM',
        subject: 'Compiler Design',
        facultyIncharge: 'Rakesh Jain',
        year: 'BE',
        class: 'A',
      },
      {
        timeSt: '9:30 AM',
        timeEnd: '10:30 AM',
        subject: 'Design Thinking',
        facultyIncharge: 'Pooja Shetty',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '10:30 AM',
        timeEnd: '11:30 AM',
        subject: 'Computer Graphics',
        facultyIncharge: 'Rajeev Taneja',
        year: 'TE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Operating Systems',
        facultyIncharge: 'Deepali Joshi',
        year: 'TE',
        class: 'A',
      },
      {
        timeSt: '1:00 PM',
        timeEnd: '2:00 PM',
        subject: 'Ethical Hacking',
        facultyIncharge: 'Sonal Shah',
        year: 'BE',
        class: 'B',
      },
      {
        timeSt: '2:00 PM',
        timeEnd: '3:00 PM',
        subject: 'Agile Methodologies',
        facultyIncharge: 'Nidhi Rao',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '3:30 PM',
        timeEnd: '4:30 PM',
        subject: 'Digital Forensics',
        facultyIncharge: 'Manoj Desai',
        year: 'BE',
        class: 'C',
      },
    ],
  },
  {
    name: '606',
    capacity: '55',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'Operating Systems',
        facultyIncharge: 'Sneha Deshmukh',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '9:30 AM',
        timeEnd: '10:30 AM',
        subject: 'Database Management',
        facultyIncharge: 'Ravi Kumar',
        year: 'BE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Python Programming',
        facultyIncharge: 'Shweta Iyer',
        year: 'TE',
        class: 'C',
      },
    ],
  },
  {
    name: '607',
    capacity: '65',
    open_time: '8:00 AM',
    close_time: '4:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '8:00 AM',
        timeEnd: '9:00 AM',
        subject: 'C Programming',
        facultyIncharge: 'Nikhil Shah',
        year: 'SE',
        class: 'A',
      },
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'OOPs',
        facultyIncharge: 'Reema Kulkarni',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Computer Networks',
        facultyIncharge: 'Ajay Menon',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '1:00 PM',
        timeEnd: '2:00 PM',
        subject: 'Web Technologies',
        facultyIncharge: 'Priya Singh',
        year: 'SE',
        class: 'C',
      },
      {
        timeSt: '3:00 PM',
        timeEnd: '4:00 PM',
        subject: 'HTML & CSS',
        facultyIncharge: 'Sunil Verma',
        year: 'SE',
        class: 'C',
      },
    ],
  },
  {
    name: '612',
    capacity: '45',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'Data Analytics',
        facultyIncharge: 'Siddharth Shinde',
        year: 'TE',
        class: 'C',
      },
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Software Project Management',
        facultyIncharge: 'Rekha Mehta',
        year: 'BE',
        class: 'A',
      },
      {
        timeSt: '2:00 PM',
        timeEnd: '3:00 PM',
        subject: 'Artificial Intelligence',
        facultyIncharge: 'Anil Mehta',
        year: 'TE',
        class: 'A',
      },
      {
        timeSt: '4:00 PM',
        timeEnd: '5:00 PM',
        subject: 'Neural Networks',
        facultyIncharge: 'Varun Singh',
        year: 'BE',
        class: 'B',
      },
    ],
  },
  {
    name: '718',
    capacity: '70',
    open_time: '9:30 AM',
    close_time: '5:30 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: false,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '9:30 AM',
        timeEnd: '10:30 AM',
        subject: 'Information Retrieval',
        facultyIncharge: 'Yogita Desai',
        year: 'TE',
        class: 'A',
      },
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'ERP',
        facultyIncharge: 'Sayali Patil',
        year: 'BE',
        class: 'A',
      },
      {
        timeSt: '11:30 AM',
        timeEnd: '12:30 PM',
        subject: 'System Programming',
        facultyIncharge: 'Ritu Agrawal',
        year: 'SE',
        class: 'B',
      },
      {
        timeSt: '2:00 PM',
        timeEnd: '3:00 PM',
        subject: 'E-Commerce',
        facultyIncharge: 'Ashwin Rao',
        year: 'BE',
        class: 'C',
      },
      {
        timeSt: '4:30 PM',
        timeEnd: '5:30 PM',
        subject: 'Startup Engineering',
        facultyIncharge: 'Tanya Verma',
        year: 'BE',
        class: 'B',
      },
    ],
  },
]

export const eventsList = [
  {
    name: 'Accenture Test',
    day: 'Tuesday',
    date: '2025-03-20', // Changed to YYYY-MM-DD
    start_time: '10:00 AM',
    end_time: '12:00 PM',
    lab_no: '304',
    facultyIncharge: 'Lydiya Miss',
    year: 'BE',
    no_of_students: '30',
    organized_by: 'TNP cell',
  },
  {
    name: 'Github Workshop',
    day: 'Wednesday',
    date: '2025-06-20', // Changed to YYYY-MM-DD
    start_time: '10:00 AM',
    end_time: '12:00 PM',
    lab_no: '306',
    facultyIncharge: 'Vikas Singh',
    year: 'TE',
    no_of_students: '30',
    organized_by: 'TSDW',
  },
  {
    name: 'Higher Studies Workshop',
    day: 'Thursday',
    date: '2025-02-20', // Changed to YYYY-MM-DD
    start_time: '10:00 AM',
    end_time: '12:00 PM',
    lab_no: '324',
    facultyIncharge: 'Shailesh Sir',
    year: 'TE',
    no_of_students: '30',
    organized_by: 'CSI',
  },
  {
    name: 'Cap Gemini Test',
    day: 'Thursday',
    date: '2025-03-21', // Changed to YYYY-MM-DD
    start_time: '10:00 AM',
    end_time: '12:00 PM',
    lab_no: '324',
    facultyIncharge: 'Lydia',
    year: 'BE',
    no_of_students: '30',
    organized_by: 'TNP',
  },
]

export const labInchargeList = [
  {
    name: 'Chetan',
    email: 'chetan@gmail.com',
    password: '123456',
    allotedLabs: ['304', '305', '306', '307', '324', '325', '326'],
    phone: '1234567890',
    photo: './profilePic.png',
    designation: 'Junior Lab Incharge',
  },
  {
    name: 'Priyanka',
    email: 'Priyanka@gmail.com',
    password: '123456',
    allotedLabs: ['304', '305', '306', '307', '324', '325', '326'],
    phone: '1234567890',
    photo: './profilePic.png',
    designation: 'Senior Lab Incharge',
  },
  {
    name: 'Vichare',
    email: 'vichare@gmail.com',
    password: '123456',
    allotedLabs: ['304', '305', '306', '307', '324', '325', '326'],
    phone: '1234567890',
    photo: './profilePic.png',
    designation: 'Senior Lab Incharge',
  },
]

export const seminarHallsData = [
  {
    id: 1,
    name: 'Auditorium',
    capacity: 500,
    location: 'Wing B , Second Floor',
    facilities: ['Projector', 'Sound System', 'Air Conditioning', 'Stage'],
    availability: 'Available',
  },
  {
    id: 2,
    name: 'Seminar Hall 1',
    capacity: 220,
    location: 'Wing C, Fifth Floor',
    facilities: ['Projector', 'Video Conferencing', 'Air Conditioning'],

    availability: 'Maintenance',
  },
  {
    id: 3,
    name: 'Seminar Hall 2',
    capacity: 150,
    location: 'Wing A, Fourth Floor',
    facilities: ['Projector', 'Video Conferencing', 'Air Conditioning'],
    availability: 'Booked',
  },
  {
    id: 4,
    name: 'Seminar Hall 3',
    capacity: 80,
    location: 'Wing B, Fourth Floor',
    facilities: ['Projector', 'Whiteboard', 'Air Conditioning'],

    availability: 'Available',
  },
  {
    id: 5,
    name: 'Seminar Hall 4',
    capacity: 200,
    location: 'Wing C, Fourth Floor',
    facilities: ['Projector', 'Sound System', 'Air Conditioning'],

    availability: 'Available',
  },
]
