export const labList = [
  {
    name: '304',
    computers: '30',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: true,
    timeTable: [
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'Software Architecture',
        facultyIncharge1: 'Tarunima Mukherjee',
        facultyIncharge2: 'Swapnil Bhagat',
        year: 'BE',
        class: 'C',
      },
    ],
  },
  {
    name: '305',
    computers: '25',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,

    timeTable: [
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Data Structures',
        facultyIncharge1: 'Rohan Gupta',
        facultyIncharge2: 'Vivek Agarwal',
        year: 'SE',
        class: 'A',
      },
    ],
  },
  {
    name: '306',
    computers: '35',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: true,
    timeTable: [
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Operating Systems',
        facultyIncharge1: 'Amit Deshmukh',
        facultyIncharge2: 'Shruti Mehta',
        year: 'TE',
        class: 'B',
      },
    ],
  },
  {
    name: '307',
    computers: '28',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '12:00 PM',
        timeEnd: '1:00 PM',
        subject: 'Computer Networks',
        facultyIncharge1: 'Snehal Gaikwad',
        facultyIncharge2: 'Rahul Shah',
        year: 'TE',
        class: 'A',
      },
    ],
  },
  {
    name: '324',
    computers: '40',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '1:00 PM',
        timeEnd: '2:00 PM',
        subject: 'Database Management',
        facultyIncharge1: 'Neha Tiwari',
        facultyIncharge2: 'Siddharth Malhotra',
        year: 'BE',
        class: 'C',
      },
    ],
  },
  {
    name: '325',
    computers: '32',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '2:00 PM',
        timeEnd: '3:00 PM',
        subject: 'Web Technologies',
        facultyIncharge1: 'Rajesh Khanna',
        facultyIncharge2: 'Anjali Sen',
        year: 'SE',
        class: 'B',
      },
    ],
  },
  {
    name: '326',
    computers: '50',
    senior_Lab_Incharge: 'Priyanka',
    jr_Lab_Incharge: 'Chetan',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    no_of_Computers_working: '30',
    projector_working: true,
    fans_working: true,
    air_conditioner_working: false,
    timeTable: [
      {
        timeSt: '3:00 PM',
        timeEnd: '4:00 PM',
        subject: 'Artificial Intelligence',
        facultyIncharge1: 'Priya Nair',
        facultyIncharge2: 'Kunal Kumar',
        year: 'TE',
        class: 'C',
      },
    ],
  },
]

export const classList = [
  {
    name: '603',
    capacity: '70',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '9:00 AM',
        timeEnd: '10:00 AM',
        subject: 'Software Architecture',
        facultyIncharge: 'Tarunima Mukherjee',
        year: 'BE',
        class: 'C',
      },
    ],
  },
  {
    name: '604',
    capacity: '50',
    open_time: '8:00 AM',
    close_time: '4:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'Data Structures',
        facultyIncharge: 'Amit Bhardwaj',
        year: 'SE',
        class: 'B',
      },
    ],
  },
  {
    name: '605',
    capacity: '60',
    open_time: '8:30 AM',
    close_time: '4:30 PM',
    computer_working: false,
    projector_working: false,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '11:00 AM',
        timeEnd: '12:00 PM',
        subject: 'Operating Systems',
        facultyIncharge: 'Deepali Joshi',
        year: 'TE',
        class: 'A',
      },
    ],
  },
  {
    name: '606',
    capacity: '55',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '9:30 AM',
        timeEnd: '10:30 AM',
        subject: 'Database Management',
        facultyIncharge: 'Ravi Kumar',
        year: 'BE',
        class: 'B',
      },
    ],
  },
  {
    name: '607',
    capacity: '65',
    open_time: '8:00 AM',
    close_time: '4:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '1:00 PM',
        timeEnd: '2:00 PM',
        subject: 'Web Technologies',
        facultyIncharge: 'Priya Singh',
        year: 'SE',
        class: 'C',
      },
    ],
  },
  {
    name: '612',
    capacity: '45',
    open_time: '9:00 AM',
    close_time: '5:00 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: true,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '2:00 PM',
        timeEnd: '3:00 PM',
        subject: 'Artificial Intelligence',
        facultyIncharge: 'Anil Mehta',
        year: 'TE',
        class: 'A',
      },
    ],
  },
  {
    name: '718',
    capacity: '70',
    open_time: '9:30 AM',
    close_time: '5:30 PM',
    computer_working: true,
    projector_working: true,
    air_conditioner_working: false,
    fans_working: true,
    lights_working: true,
    timeTable: [
      {
        timeSt: '10:00 AM',
        timeEnd: '11:00 AM',
        subject: 'ERP',
        facultyIncharge: 'Sayali Patil',
        year: 'BE',
        class: 'A',
      },
    ],
  },
]
